<?php

define('VERDURE_RESTAURANT_VERSION', '1.0');
define('VERDURE_RESTAURANT_ABS_PATH', dirname(__FILE__));
define('VERDURE_RESTAURANT_REL_PATH', dirname(plugin_basename(__FILE__ )));
define('VERDURE_RESTAURANT_URL_PATH', plugin_dir_url( __FILE__ ));
define('VERDURE_RESTAURANT_ASSETS_PATH', VERDURE_RESTAURANT_ABS_PATH.'/assets');
define('VERDURE_RESTAURANT_ASSETS_URL_PATH', VERDURE_RESTAURANT_URL_PATH.'assets');
define('VERDURE_RESTAURANT_CPT_PATH', VERDURE_RESTAURANT_ABS_PATH.'/post-types');
define('VERDURE_RESTAURANT_SHORTCODES_PATH', VERDURE_RESTAURANT_ABS_PATH.'/modules/shortcodes');